name: Send Email

on:
  pull_request:
    branches: [ main ]

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: hello
        run: echo "Hello Github Actions"

      - name: checkout
        uses: actions/checkout@v2

      - name: install flake8
        run: pip3 install flake8
        
      - name: Run flake8
        run: flake8 --statistics
